### ISSUE TITLE
Show Pearson's R correlation between Xanthos and VIC global mean runoff

### ISSUE THREAD

**Issue by evanoffPNNL** [JGCRI/xanthosvis#1]
Duplicate the graph from slack channel that shows the comparison between Xanthos and VIC and the linear correlation.

**Comment by evanoffPNNL** [comment]
![image](https://user-images.githubusercontent.com/50331146/83036674-e9263800-a008-11ea-9656-8b40a8e4ae05.png)

**Comment by crvernon** [comment]
Outdated
